name: Push GHCR Image to AWS ECR

on:
  workflow_dispatch:  # ìˆ˜ë™ ì‹¤í–‰ ê°€ëŠ¥í•˜ê²Œ

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: ecr-timbel-rabbitmq # â† ë°›ì€ ì •ë³´ë¡œ ë³€ê²½
  GHCR_IMAGE: ghcr.io/mintaekkim/rabbitmq  # â† ì‹¤ì œ GHCR ì´ë¯¸ì§€ë¡œ ë³€ê²½
  IMAGE_TAG: 3-management

jobs:
  push-to-ecr:
    name: Pull from GHCR and Push to ECR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code (optional)
      uses: actions/checkout@v4

    - name: Docker Login to GHCR
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u mintaekkim --password-stdin

    - name: Pull image from GHCR
      run: docker pull $GHCR_IMAGE:$IMAGE_TAG

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Tag and Push image to ECR
      run: |
        ECR_URI=${{ steps.login-ecr.outputs.registry }}/${ECR_REPOSITORY}
        echo "ğŸ³ Tagging image from $GHCR_IMAGE:$IMAGE_TAG"
        echo "ğŸ“¦ Tagging to $ECR_URI:$IMAGE_TAG"
        docker images  # ë””ë²„ê¹…ìš© ì¶œë ¥
        docker tag $GHCR_IMAGE:$IMAGE_TAG $ECR_URI:$IMAGE_TAG
        docker push $ECR_URI:$IMAGE_TAG

